pipeline {
    agent any
    stages {
        stage('Clone Repo') {
            steps {
                git branch: 'main', url: 'https://github.com/L1bun/devsecops-pipeline.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t devsecops-app ./app'
            }
        }
        stage('OWASP Security Scan') {
            steps {
                sh '''
                    docker run --rm \
                    -v $(pwd):/src \
                    owasp/dependency-check \
                    --scan /src \
                    --format HTML \
                    --out /src/security-report
                '''
            }
        }
        stage('Run Container') {
            steps {
                sh 'docker run -d -p 5000:5000 devsecops-app'
            }
        }
    }
    post {
        always {
            echo 'Pipeline completed!'
        }
        success {
            echo 'Build succeeded!'
        }
        failure {
            echo 'Build failed!'
        }
    }
}
